# Use an official Python runtime as a parent image #
FROM python:3.12-slim

# Set the working directory inside the container #
WORKDIR /app

ARG SERVER_FOLDER=./server

# Copy the custom server script into the container
COPY $SERVER_FOLDER/requirements.txt ./requirements.txt
COPY $SERVER_FOLDER/test_sinergym_flwr_server.py ./server.py

COPY $SERVER_FOLDER/flwr_dr_server.py ./flwr_dr_server.py

# Install any necessary Python packages #
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install deap==1.4.1

# Expose the port that Flower server will run on (default 8080) #
EXPOSE 8080

# Run the entrypoint script when the container starts
COPY $SERVER_FOLDER/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["--default-arg"]
